package run.halo.aifoundation.tool;

import reactor.core.publisher.Mono;

/**
 * Server-side implementation for a {@link ToolDefinition}.
 *
 * <p>The context contains parsed JSON arguments generated by the model plus call metadata such as
 * tool call id, step index, and provider-neutral messages. Return values should be JSON
 * serializable because Halo sends them back to the model as a tool response.
 */
@FunctionalInterface
public interface ToolExecutor {
    /**
     * Executes the tool.
     *
     * @param context execution context including parsed tool arguments
     * @return a mono that emits the tool result
     */
    Mono<Object> execute(ToolExecutionContext context);
}
