apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-ai-foundation-manage
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "AI Foundation"
    rbac.authorization.halo.run/display-name: "AI Foundation 管理"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:ai-foundation:manage"]
rules:
  - apiGroups: ["aifoundation.halo.run"]
    resources: ["aiproviders", "aimodels"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: ["console.api.aifoundation.halo.run"]
    resources: ["*"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
---
apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-ai-foundation-view
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "AI Foundation"
    rbac.authorization.halo.run/display-name: "AI Foundation 查看"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:ai-foundation:view"]
rules:
  - apiGroups: ["aifoundation.halo.run"]
    resources: ["aiproviders", "aimodels"]
    verbs: ["get", "list"]
  - apiGroups: ["console.api.aifoundation.halo.run"]
    resources: ["*"]
    verbs: ["get", "list"]
