# Refer https://docs.halo.run/developer-guide/plugin/basics/manifest

apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: ai-foundation
spec:
  enabled: true
  requires: ">=2.23.0"
  author:
    name: Halo
    website: https://github.com/halo-dev
  logo: icon.png
  configMapName: ai-foundation-configmap
  homepage: https://github.com/halo-dev/plugin-ai-foundation#readme
  repo: https://github.com/halo-dev/plugin-ai-foundation
  issues: https://github.com/halo-dev/plugin-ai-foundation/issues
  displayName: "AI Foundation"
  description: "Halo 官方 AI 能力平台，统一接入主流大模型，为插件生态提供文本生成、嵌入向量、工具调用等智能化能力"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/halo-dev/plugin-ai-foundation/blob/main/LICENSE"
