package run.halo.aifoundation.part;

import java.util.Map;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Reasoning content generated by a language model.
 *
 * <p>Reasoning is kept separate from final answer text. Some providers expose it as visible
 * thinking text, while others use it mainly as state that must be passed back when continuing a
 * tool-calling conversation. Normal callers should read {@link #text}; provider-specific metadata
 * is optional, namespaced, and opaque unless the provider documents otherwise.
 *
 * <pre>{@code
 * var request = GenerateTextRequest.builder()
 *     .messages(List.of(ModelMessage.assistant(List.of(
 *         ModelMessagePart.reasoning(ReasoningPart.builder()
 *             .text("I need to look up the weather.")
 *             .build()),
 *         ModelMessagePart.toolCall(toolCall)
 *     ))))
 *     .build();
 * }</pre>
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ReasoningPart {
    /**
     * Visible reasoning text when the provider exposes it.
     */
    private String text;
    /**
     * Optional provider signature for reasoning content, when the provider returns one.
     */
    private String signature;
    /**
     * Provider-specific metadata associated with the reasoning part. Values must be sanitized and
     * serializable.
     */
    private Map<String, Object> providerMetadata;
}
