package run.halo.aifoundation;

import java.util.Map;
import reactor.core.publisher.Mono;

/**
 * Server-side implementation for a {@link ToolDefinition}.
 *
 * <p>The input map contains parsed JSON arguments generated by the model. Return values should be
 * JSON serializable because Halo sends them back to the model as a tool response.
 */
@FunctionalInterface
public interface ToolExecutor {
    /**
     * Executes the tool.
     *
     * @param input parsed tool arguments
     * @return a mono that emits the tool result
     */
    Mono<Object> execute(Map<String, Object> input);
}
